<script setup lang="ts">
import{onMounted,ref}from'vue';import{http,mediaUrl}from'../api/http'
const items=ref<any[]>([]),selected=ref<any>(),albums=ref<any[]>([]),target=ref(''),date=ref('')
async function load(){items.value=(await http.get('/recycle')).data;albums.value=(await http.get('/albums')).data}
function open(item:any){selected.value=item;target.value=item.originAlbum;const s=String(item.originDate);date.value=`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`}
async function restore(){await http.post(`/recycle/${selected.value.id}/restore`,{albumKey:target.value,date:Number(date.value.replaceAll('-',''))});selected.value=null;await load()}
async function remove(){if(!confirm('⚠️ 高能预警\n\n确定要【永久彻底】删除这张照片吗？\n删除后将无法找回！'))return;await http.delete(`/recycle/${selected.value.id}`);selected.value=null;await load()}
onMounted(load)
</script>
<template><main class="recycle-page"><div class="header"><h1>♻️ 回收站</h1><router-link to="/" class="btn-back">返回</router-link></div><div class="grid"><button v-for="item in items" :key="item.id" class="item" @click="open(item)"><img :src="mediaUrl(item.previewPath)" loading="lazy"><span>{{item.originAlbum}} / {{item.originDate}}</span></button><p v-if="!items.length" class="empty">这里空空如也 🍃</p></div>
<div v-if="selected" class="detail"><button class="close" @click="selected=null">✕</button><div class="img-container"><img :src="mediaUrl(selected.rawPath)"></div><div class="panel"><div class="info"><b>原位置:</b> {{selected.originAlbum}} / {{selected.originDate}}<br><template v-if="selected.photoTime"><b>拍摄时间:</b> {{selected.photoTime}}<br></template><b>删除时间:</b> {{selected.deletedAt}}</div><div class="form-row"><select v-model="target"><option v-for="a in albums" :key="a.key" :value="a.key">{{a.label}}</option></select><input v-model="date" type="date"></div><button class="action restore" @click="restore">✨ 恢复照片</button><button class="action delete" @click="remove">🗑️ 彻底粉碎</button></div></div>
</main></template>
<style scoped>.recycle-page{min-height:100vh;background:#f0f2f5;padding:20px}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.header h1{font-size:22px}.btn-back{text-decoration:none;padding:8px 16px;background:#333;color:#fff;border-radius:20px;font-size:14px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:10px}.item{position:relative;aspect-ratio:1;background:#ddd;border-radius:8px;overflow:hidden;border:2px solid transparent;padding:0}.item:active{transform:scale(.95)}.item img{width:100%;height:100%;object-fit:cover}.item span{position:absolute;bottom:0;left:0;right:0;background:rgba(0,0,0,.6);color:#fff;font-size:10px;padding:4px}.empty{text-align:center;grid-column:1/-1;color:#999;margin-top:50px}.detail{position:fixed;inset:0;background:#000;color:#fff;z-index:200;display:flex;flex-direction:column}.img-container{flex:1;display:flex;justify-content:center;align-items:center;overflow:hidden;padding:20px}.img-container img{max-width:100%;max-height:100%;object-fit:contain;border-radius:4px}.panel{background:#1e1e1e;padding:20px 20px 40px;border-radius:16px 16px 0 0}.info{color:#888;font-size:12px;margin-bottom:20px;text-align:center;line-height:1.6}.form-row{display:flex;gap:10px;margin-bottom:15px}.form-row select,.form-row input{flex:1;padding:12px;border-radius:8px;border:1px solid #444;background:#333;color:#fff;font-size:14px}.action{width:100%;padding:14px;border:0;border-radius:50px;font-size:16px;font-weight:bold;color:#fff;margin-bottom:10px}.restore{background:#07c160}.delete{background:#ff4757;margin-top:10px}.close{position:absolute;top:20px;right:20px;z-index:10;width:36px;height:36px;background:rgba(255,255,255,.2);border:0;border-radius:50%;color:#fff;font-size:20px}</style>
