<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Sortable from 'sortablejs'
import { http } from '../api/http'
import { detectPhotoTime } from '../utils/photoTime'
import { isVideoFile } from '../utils/media'

type Photo={uid:string;file:File;src:string;time:string;cover:boolean;video:boolean}
const router=useRouter(),route=useRoute(),album=sessionStorage.getItem('currentAlbum')||'peachwuhu'
const info=ref(''),date=ref(String(route.query.date||'').replace(/(....)(..)(..)/,'$1-$2-$3')),photos=ref<Photo[]>([])
const loading=ref(''),grid=ref<HTMLElement>(),dateWarning=ref(false)
onMounted(()=>{if(grid.value)new Sortable(grid.value,{animation:150,filter:'.static-item',delay:200,delayOnTouchOnly:true})})
async function choose(event:Event){const files=[...(event.target as HTMLInputElement).files||[]];const dates=new Set<string>();for(const file of files){const uid=`${file.name}-${file.size}-${Date.now()}-${Math.random()}`;const time=await detectPhotoTime(file);if(time)dates.add(time.slice(0,10));photos.value.push({uid,file,src:URL.createObjectURL(file),time,cover:false,video:isVideoFile(file)})}const sorted=[...dates].sort();if(sorted[0]&&(!date.value||sorted[0]<date.value))date.value=sorted[0];dateWarning.value=dates.size>1;(event.target as HTMLInputElement).value='';await nextTick()}
function toggle(photo:Photo){const count=photos.value.filter(x=>x.cover).length;if(!photo.cover&&count>=9)return alert('封面最多只能选择 9 张');photo.cover=!photo.cover}
function sort(){photos.value.sort((a,b)=>a.time&&b.time?a.time.localeCompare(b.time):a.time?-1:b.time?1:0)}
async function publish(){if(!date.value)return alert('请选择拍摄日期');if(!photos.value.length)return alert('请至少选择一个照片或视频');const covers=photos.value.filter(x=>x.cover);if(covers.length&&![1,3,4,8,9].includes(covers.length))return alert('封面数量只能是 1、3、4、8 或 9 个');const ordered=[...document.querySelectorAll<HTMLElement>('.grid-item:not(.static-item)')].map(el=>photos.value.find(x=>x.uid===el.dataset.uid)!).filter(Boolean);const form=new FormData();form.append('date',date.value.replaceAll('-',''));form.append('info',info.value);form.append('updateInfo','true');ordered.forEach(p=>{form.append('photoUids',p.uid);form.append('photoTimes',p.time);form.append('photos',p.file)});covers.forEach(p=>form.append('coverUids',p.uid));loading.value='准备上传...';await http.post(`/albums/${album}/images`,form,{onUploadProgress:e=>loading.value=`正在上传... ${Math.round((e.loaded/(e.total||e.loaded))*100)}%`});sessionStorage.setItem('uploadSuccessMessage',`${date.value}上传成功，共${photos.value.length}个媒体文件`);await router.push('/')}
</script>
<template><main class="upload-page">
  <div class="loading-overlay" :class="{show:loading}"><div class="spinner"/><div class="loading-text">{{loading}}</div></div>
  <div class="navbar"><a class="cancel-btn" @click="router.back()">取消</a><div class="nav-actions"><button class="sort-btn" @click="sort">整理</button><button class="save-btn" @click="publish">发表</button></div></div>
  <div class="container"><div class="text-area-wrapper"><textarea v-model="info" class="story-input" placeholder="这一刻的想法..."/></div>
    <div ref="grid" class="grid">
      <div v-for="photo in photos" :key="photo.uid" class="grid-item fade-in" :class="{'cover-selected':photo.cover}" :data-uid="photo.uid" :data-photo-time="photo.time"><video v-if="photo.video" :src="photo.src" muted playsinline preload="metadata"/><img v-else :src="photo.src"><span v-if="photo.video" class="play-badge">▶</span><div v-if="photo.time" class="photo-time-tag">{{photo.time}}</div><button class="cover-btn" @click.stop="toggle(photo)">封面</button><button class="delete-btn" @click.stop="photos=photos.filter(x=>x!==photo)">✕</button></div>
      <div class="grid-item add-photo-item static-item"><span class="add-icon">+</span><input type="file" class="overlay-file-input" multiple accept="image/*,video/*" @change="choose"></div>
    </div>
    <div class="meta-list"><label class="meta-row"><div class="meta-label"><span class="meta-icon">📅</span> 拍摄日期</div><div class="meta-value-wrapper"><span>{{date||'选择日期'}}</span><span class="arrow-icon">›</span></div><input v-model="date" type="date" class="hidden-date-input"></label><div v-if="dateWarning" class="date-warning-text">⚠️ 照片日期不一致，已自动选择最早的日期</div></div>
  </div>
</main></template>
<style scoped>
.upload-page{min-height:100vh;padding-top:50px}.navbar{position:fixed;top:0;left:0;width:100%;height:50px;background:rgba(255,255,255,.98);border-bottom:.5px solid #eee;display:flex;align-items:center;justify-content:space-between;padding:0 15px;z-index:100}.cancel-btn{color:#333;font-size:16px;cursor:pointer}.nav-actions{display:flex;gap:8px}.sort-btn{border:1px solid #ddd;background:#fff;color:#555;padding:6px 10px;border-radius:4px;font-size:13px}.save-btn{border:0;background:#07c160;color:#fff;padding:6px 14px;border-radius:4px;font-size:14px;font-weight:bold}.container{padding:20px}.text-area-wrapper{margin-bottom:20px}.story-input{width:100%;min-height:100px;border:0;background:transparent;font-size:16px;line-height:1.5;resize:none;outline:0}.grid{display:grid;gap:8px;grid-template-columns:repeat(3,1fr);margin-bottom:30px}.grid-item{position:relative;aspect-ratio:1;border-radius:4px;overflow:hidden;background:#f2f2f2;user-select:none}.grid-item img{width:100%;height:100%;object-fit:cover;display:block;pointer-events:none}.cover-selected{box-shadow:inset 0 0 0 3px #2f7cff}.photo-time-tag{position:absolute;bottom:4px;left:5px;color:rgba(255,255,255,.95);font-size:10px;font-weight:600;z-index:5;text-shadow:0 1px 2px rgba(0,0,0,.8)}.cover-btn{position:absolute;top:2px;left:2px;min-width:42px;height:20px;padding:0 6px;border:0;border-radius:10px;background:rgba(0,0,0,.4);color:#fff;font-size:11px}.cover-selected .cover-btn{background:#2f7cff}.delete-btn{position:absolute;top:2px;right:2px;width:20px;height:20px;background:rgba(0,0,0,.4);color:#fff;border-radius:50%;border:0}.add-photo-item{background:#f7f7f7;display:flex;align-items:center;justify-content:center}.add-icon{font-size:40px;color:#ddd;font-weight:300}.overlay-file-input{position:absolute;inset:0;width:100%;height:100%;opacity:0;z-index:20}.meta-list{border-top:.5px solid #eee;margin:0 -20px;padding:0 20px}.meta-row{display:flex;align-items:center;justify-content:space-between;height:55px;border-bottom:.5px solid #eee;position:relative}.meta-label{display:flex;align-items:center;font-size:15px}.meta-icon{margin-right:10px;font-size:18px}.meta-value-wrapper{display:flex;align-items:center;color:#999;font-size:14px}.arrow-icon{margin-left:8px;color:#ccc}.hidden-date-input{position:absolute;inset:0;width:100%;height:100%;opacity:0}.date-warning-text{font-size:12px;color:#ff3b30;margin-top:5px;padding:0 5px}.loading-overlay{position:fixed;inset:0;background:rgba(255,255,255,.8);backdrop-filter:blur(5px);display:flex;flex-direction:column;align-items:center;justify-content:center;z-index:999;opacity:0;pointer-events:none}.loading-overlay.show{opacity:1;pointer-events:auto}.spinner{width:40px;height:40px;border:4px solid #07c160;border-top-color:#b2e6c6;border-radius:50%;animation:spin 1s linear infinite}.loading-text{margin-top:15px;color:#666;font-size:14px;font-weight:bold}@keyframes spin{to{transform:rotate(360deg)}}
.grid-item video{width:100%;height:100%;object-fit:cover;display:block;pointer-events:none}.play-badge{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:rgba(0,0,0,.55);color:#fff;font-size:18px;padding-left:3px;z-index:4}
</style>
